name: Build & Release

on:
  push:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Increment Version
        run: |
          chmod +x scripts/increment_version.sh
          ./scripts/increment_version.sh

      - name: Generate Changelog
        run: |
          chmod +x scripts/generate_changelog.sh
          ./scripts/generate_changelog.sh

      - name: Commit & Push Version Bump
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add pubspec.yaml CHANGELOG.md
          git commit -m "Bump version & update changelog [skip ci]"
          git push


      - name: Build APK (Dev)
        if: github.ref == 'refs/heads/develop'
        run: flutter build apk --release -t lib/main_dev.dart

      - name: Build APK (Prod)
        if: github.ref == 'refs/heads/main'
        run: flutter build apk --release -t lib/main_prod.dart

      - name: Upload Artifacts (Dev)
        if: github.ref == 'refs/heads/develop'
        uses: actions/upload-artifact@v4
        with:
          name: app-dev-release
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload Artifacts (Prod)
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: app-prod-release
          path: build/app/outputs/flutter-apk/app-release.apk
